### PR TITLE
Update design

### PR DESCRIPTION
**Pull request by scabbiaza**
Update fonts: use Roboto Slab for headers and Roboto Condensed for logo (close issue #2).
Update colors.
Update header: make it dark metallic.
Add effect to main menu.

### CODE REVIEW

**Comment by ivan-kleshnin** [comment]
http://subtlepatterns.com/dark-embroidery/
http://subtlepatterns.com/small-steps/
http://subtlepatterns.com/escheresque-dark/

**Comment by scabbiaza** [comment]
Will try this titles. Thank you

**Comment by scabbiaza** [comment]
http://puu.sh/fZJ2I.png
http://puu.sh/fZJ57.png
http://puu.sh/fZJ7v.png

**Comment by ivan-kleshnin** [comment]
I'd like to also see this http://puu.sh/fZJ7v.png in reverse colors. May be cool

**Pull request merged**
